---
solver:
  type: vqa
  pqc:
    type: wfqaoa
    layers: 5
    penalty: 3
  params_inits:
    angles: [[0.5, 0.5, 0.5, 0.5, 0.5], [1, 1, 1, 1, 1]]
    hyper_args: [1, 2.5, 2.5]
  hyper_optimizer:
    type: cem
    processes: 5
    samples_per_epoch: PLACEHOLDER
    epochs: PLACEHOLDER
    elite_frac: PLACEHOLDER
    bounds: [[1, 10], [1, 10], [1, 10]]
    disable_tqdm: true
problem:
  type: knapsack
  max_weight: 2
  items: [[1, 2], [1, 2], [1, 1]]
